### PR TITLE
fixed the wrong color on issues page

### PR DESCRIPTION
**Pull request by AlexGopal**
The color in the issues list was too light so it was changed to a darker color.

### CODE REVIEW

**Comment by mentor-tara** [comment]
You need to be a premium member for this task. Please head to [profy.dev](https://profy.dev#premium) and upgrade your account. Once you're done request another review.

**Review by mentor-tara — APPROVED** [review]
Go go go :smile:[](prolog-2)

**Comment by AlexGopal** [comment]
Fixed color issue.

**Comment by mentor-tara** [comment]
You need to be a premium member for this task. Please head to [profy.dev](https://profy.dev#premium) and upgrade your account. Once you're done request another review.

**Pull request merged**
